apiVersion: v1
kind: Namespace
metadata:
  name: offloading-measurer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: offloading-measurer
  namespace: offloading-measurer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: offloading-measurer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: offloading-measurer
  namespace: offloading-measurer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: offloading-measurer
  namespace: offloading-measurer
  labels:
    app.kubernetes.io/name: offloading-measurer
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: offloading-measurer
    spec:
      containers:
      - image: giorio94/liqo-offloading-measurer:v0.4.0
        imagePullPolicy: IfNotPresent
        name: offloading-measurer
        args:
        - --namespace=offloading-benchmark
        - --deployments=__DEPLOYS__
        - --pods=__PODS__
        - --affinity=node-role.kubernetes.io/hollow=true
        - --v=2
      dnsPolicy: Default
      restartPolicy: OnFailure
      serviceAccountName: offloading-measurer
