{{- $config := (merge (dict "component" "hub") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo-k3s-cattle.fullname" . }}-hub
  labels:
    {{- include "liqo-k3s-cattle.labels" $config | nindent 4 }}
spec:
  replicas: {{ .Values.hub.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "liqo-k3s-cattle.selectorLabels" $config | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo-k3s-cattle.selectorLabels" $config | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: k3s-server
        image: {{ .Values.hub.image }}
        command:
        - /bin/k3s
        args:
        - server
        - --tls-san=0.0.0.0
        - --datastore-endpoint=etcd
        - --disable-network-policy
        - --disable=traefik
        - --disable=local-storage
        - --kubelet-arg=config=/etc/rancher/k3s/kubelet-config.yaml
        - --cluster-cidr=10.42.0.0/20
        - --service-cidr=10.43.0.0/20
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.hub.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /readiness-check
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
        - containerPort: 6443
          name: apiserver
          protocol: TCP
        volumeMounts:
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-namespace.yaml
          subPath: liqo-namespace.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-chart.yaml
          subPath: liqo-chart.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-warm-up-job.yaml
          subPath: liqo-warm-up-job.yaml
        {{- if .Values.peeringMeasurer.enabled }}
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-peering-measurer-namespace.yaml
          subPath: liqo-peering-measurer-namespace.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-peering-measurer-service-account.yaml
          subPath: liqo-peering-measurer-service-account.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-peering-measurer-cluster-role-binding.yaml
          subPath: liqo-peering-measurer-cluster-role-binding.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-peering-measurer-job.yaml
          subPath: liqo-peering-measurer-job.yaml
        {{- end }}
        {{- if .Values.consumptionMeasurer.enabled }}
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-consumption-measurer-namespace.yaml
          subPath: liqo-consumption-measurer-namespace.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-consumption-measurer-job.yaml
          subPath: liqo-consumption-measurer-job.yaml
        {{- end }}
        - name: configuration
          mountPath: /etc/rancher/k3s/kubelet-config.yaml
          subPath: kubelet-config.yaml
        - name: configuration
          mountPath: /etc/rancher/k3s/registries.yaml
          subPath: registries.yaml
        - name: configuration
          mountPath: /proc/meminfo
          subPath: meminfo
        - name: configuration
          mountPath: /readiness-check
          subPath: readiness-check
        - name: database
          mountPath: /var/lib/rancher/k3s/server/db
      {{- if .Values.networkMeasurer.enabled }}
      - name: network-measurer
        image: {{ .Values.networkMeasurer.image }}
        args:
        - --target-service={{ include "liqo-k3s-cattle.fullname" . }}-minion
        - --expected={{ .Values.minion.replicaCount }}
        - --target-port=6443
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1000m
            memory: 100Mi
      {{- end }}
      volumes:
      - name: configuration
        configMap:
          name: {{ include "liqo-k3s-cattle.fullname" . }}
          defaultMode: 400
      - name: database
        emptyDir:
          medium: "Memory"
      affinity:
        {{- toYaml .Values.hub.affinity | nindent 8 }}
