{{- $config := (merge (dict "component" "minion") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo-k3s-cattle.fullname" . }}-minion
  labels:
    {{- include "liqo-k3s-cattle.labels" $config | nindent 4 }}
spec:
  replicas: {{ .Values.minion.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "liqo-k3s-cattle.selectorLabels" $config | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo-k3s-cattle.selectorLabels" $config | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
      - name: k3s-server
        image: {{ .Values.minion.image }}
        command:
        - /bin/k3s
        args:
        - server
        - --tls-san=0.0.0.0
        - --datastore-endpoint=etcd
        - --disable-network-policy
        - --disable=traefik
        - --disable=local-storage
        - --cluster-cidr=10.42.0.0/20
        - --service-cidr=10.43.0.0/20
        securityContext:
          privileged: true
        resources:
          {{- toYaml .Values.minion.resources | nindent 10 }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /readiness-check
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
        - containerPort: 6443
          name: apiserver
          protocol: TCP
        volumeMounts:
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-namespace.yaml
          subPath: liqo-namespace.yaml
        - name: configuration
          mountPath: /var/lib/rancher/k3s/server/manifests/liqo-chart.yaml
          subPath: liqo-chart.yaml
        - name: configuration
          mountPath: /etc/rancher/k3s/registries.yaml
          subPath: registries.yaml
        - name: configuration
          mountPath: /proc/meminfo
          subPath: meminfo
        - name: configuration
          mountPath: /readiness-check
          subPath: readiness-check
        - name: database
          mountPath: /var/lib/rancher/k3s/server/db
      volumes:
      - name: configuration
        configMap:
          name: {{ include "liqo-k3s-cattle.fullname" . }}
          defaultMode: 400
      - name: database
        emptyDir:
          medium: "Memory"
      affinity:
        {{- toYaml .Values.minion.affinity | nindent 8 }}
