{{- $config := (merge (dict "component" "kubeconfig-retriever") .) -}}
{{ $fullname := printf "%s-kubeconfig-retriever" ( include "liqo-k3s-hollow.fullname" $ ) -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "liqo-k3s-hollow.labels" $config | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "liqo-k3s-hollow.labels" $config | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "liqo-k3s-hollow.labels" $config | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullname }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "liqo-k3s-hollow.labels" $config | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  {{- $providerconfig := (merge (dict "component" "provider") .) -}}
  {{- $raw := include "liqo-k3s-hollow.selectorLabels" $providerconfig }}
  {{- $labels := include "liqo-k3s-hollow.concatenate" $raw }}
  retrieve.sh: |-
    set -ex

    KUBECTL="kubectl --cache-dir=/tmp/.kube/cache"

    SCRNAME={{ include "liqo-k3s-hollow.fullname" . }}-provider-kubeconfig
    $KUBECTL delete secret $SCRNAME --ignore-not-found

    $KUBECTL wait pod --for=condition=ready -l {{ $labels }} --timeout=120s
    PODNAME=$($KUBECTL get po -l {{ $labels }} -o custom-columns=':metadata.name' --no-headers)
    PODIP=$($KUBECTL get po -l {{ $labels }} -o custom-columns=':status.podIP' --no-headers)

    $KUBECTL cp $PODNAME:/etc/rancher/k3s/k3s.yaml /tmp/kubeconfig
    sed -i "s|127.0.0.1|$PODIP|" /tmp/kubeconfig
    $KUBECTL create secret generic $SCRNAME --from-file=/tmp/kubeconfig
{{- range $key, $val := ( $raw | fromYaml ) }}
    $KUBECTL label secret $SCRNAME {{ $key }}={{ $val }}
{{- end }}
    $KUBECTL annotate secret $SCRNAME helm.sh/hook-delete-policy=before-hook-creation
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "liqo-k3s-hollow.labels" $config | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ $fullname }}
      labels:
        {{- include "liqo-k3s-hollow.selectorLabels" $config | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ $fullname }}
      containers:
      - name: kubectl
        image: {{ .Values.hollow.kubectlImage }}
        command:
          - /bin/bash
        args:
          - /tmp/retrieve.sh
        volumeMounts:
          - name: retriever
            mountPath: /tmp/retrieve.sh
            subPath: retrieve.sh
      volumes:
        - name: retriever
          configMap:
            name: {{ $fullname }}
