hub:
  replicaCount: 1
  image: rancher/k3s:v1.21.3-k3s1

  resources:
    limits:
      cpu: 8000m
      memory: 32768Mi
    requests:
      cpu: 8000m
      memory: 32768Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-1


minion:
  replicaCount: 1
  image: rancher/k3s:v1.21.3-k3s1

  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 1000m
      memory: 2048Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - worker-1


peeringMeasurer:
  enabled: true
  image: giorio94/liqo-peering-measurer:v0.4.0
  namespace: peering-measurer

consumptionMeasurer:
  enabled: false
  image: giorio94/liqo-consumption-measurer:v0.3.0
  namespace: consumption-measurer

networkMeasurer:
  enabled: false
  image: giorio94/liqo-network-measurer:v0.0.1

settings:
  proxyRegistry: http://docker-registry:5000
  memTotalGB: 32
  maxPods: 250

extraLatency:
  enabled: false
  image: giorio94/tc:0.1
  delay: 100ms

liqo:
  repo: ""
  chart: https://crownlabs.polito.it/cloud/s/y7JRSXGF2JiZwxo/download
  version: ""

  namespace: liqo

  pull:
    kubelet: liqo/virtual-kubelet-ci:b3099f20fea4cf97925bfc2dd18a7b7f8c7ede51
    kubeletInit: liqo/init-virtual-kubelet-ci:b3099f20fea4cf97925bfc2dd18a7b7f8c7ede51

  values: |
    tag: "b3099f20fea4cf97925bfc2dd18a7b7f8c7ede51"

    controllerManager:
      config:
        resourceSharingPercentage: 100
      pod:
        extraArgs:
          - --v=4
          - --kubelet-cpu-limits=250m
          - --kubelet-cpu-requests=25m
          - --kubelet-ram-limits=250M
          - --kubelet-ram-requests=50M
          - --foreign-cluster-workers=3

    networkManager:
      config:
        podCIDR: "10.42.0.0/20"
        serviceCIDR: "10.43.0.0/20"
        reservedSubnets:
        - 192.168.0.0/16
        - 172.16.0.0/16
        - 10.96.0.0/12
      pod:
        extraArgs:
          - --v=4

    gateway:
      service:
        type: NodePort

    auth:
      config:
        enableAuthentication: false
      service:
        type: LoadBalancer
      pod:
        extraArgs:
          - --v=4

    discovery:
      config:
        clusterName: liqo-cluster
        enableAdvertisement: false
        enableDiscovery: false

    crdReplicator:
      pod:
        extraArgs:
          - --v=4
